FROM python:3.12-slim-bullseye

RUN apt-get update && apt-get install -y curl unzip  && rm -rf /var/lib/apt/lists/*
ARG SJP_COMMIT=main
WORKDIR /StaticJinjaPlus/

RUN if [ "$SJP_COMMIT" = "main" ]; then \
        URL="https://github.com/MrDave/StaticJinjaPlus/archive/refs/heads/$SJP_COMMIT.zip"; \
    else \
        URL="https://github.com/MrDave/StaticJinjaPlus/archive/refs/tags/$SJP_COMMIT.zip"; \
    fi && \
    curl -L $URL -o staticjinjaplus.zip && \
    unzip staticjinjaplus.zip && \
    rm staticjinjaplus.zip && \
    mv StaticJinjaPlus-$SJP_COMMIT/* . && \
    rm -rf StaticJinjaPlus-$SJP_COMMIT
RUN pip install --break-system-packages --no-cache-dir -r requirements.txt
ARG TEMPLATE_FOLDER=templates
ENV TEMPLATE_FOLDER=${TEMPLATE_FOLDER}
COPY ./$TEMPLATE_FOLDER ./$TEMPLATE_FOLDER
CMD sh -c "python main.py -w --srcpath ${TEMPLATE_FOLDER}"


